### ISSUE TITLE
Server Error with Phoenix 1.4 when status: is specified

### ISSUE THREAD

**Issue by mikehostetler** [lpil/plug-redirect#2]
I'm using `plug-redirect` with Phoenix 1.4.  I followed install instructions and a basic 301 redirect works, when no status code is specified.  I am on Elixir 1.7.3.

`redirect "/ada", "/lovelace"`

However, when I specify a status code in my Redirection module, I get a Internal Server error:

`redirect "/grace", "/hopper", status: 302`

The error is:

```
== Compilation error in file lib/mw_web/redirects.ex ==
** (FunctionClauseError) no function clause matching in Plug.Redirect.redirect/3
    (plug_redirect) expanding macro: Plug.Redirect.redirect/3
    lib/mw_web/redirects.ex:9: MwWeb.Redirector (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

I've downloaded and run all of the tests in this module with my version of Elixir and all tests pass.

I created a brand new Phoenix install with 1.4 and the problem persists.

Is it possible that the the `redirect/3` function conflicts with the Redirect function already in Phoenix?

**Comment by lpil** [comment]
Could you share the full module please? 

This library is intended to be used in a fresh module, not one with the Phoenix DSL imported.

**Comment by mikehostetler** [comment]
Here's the line in my Applications `Endpoint.ex`:

```
defmodule MwWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mw

  # Initiate our redirects!
  plug(MwWeb.Redirector)

  ... (other endpoint code)
end
```

Redirector Module:
```
defmodule MwWeb.Redirector do
  use Plug.Redirect

  # Argument #1 is the path to redirect from
  # Argument #2 is the path to redirect to
  redirect "/ada", "/lovelace"

  # Redirect with a Status Code
  redirect "/grace", "/hopper", status: 302
end
```

**Comment by lpil** [comment]
Could you provide an example project? I'm unable to reproduce the error.

The code you have given is verified in the tests as far as I can see https://github.com/lpil/plug-redirect/blob/master/test/plug/redirect_test.exs

**Comment by mikehostetler** [comment]
I tossed up a quick example here: https://github.com/mikehostetler/mw_redirect_web

I was able to re-create the issue locally again

**Comment by lpil** [comment]
Seems the documentation is for a version I forgot to release 3 years ago. How embarrassing. I'll fix this now.

**Comment by mikehostetler** [comment]
Works great, thanks!!!
