### ISSUE TITLE
Handling query parameter urls

### ISSUE THREAD

**Issue by colindensem** [lpil/plug-redirect#4]
Hi @lpil,

We've been using this library for a few years, although I'm new to elixir and the company. We wanted to handle some rewrites for query param based urls.

For example:
```
redirect("/pages?type=modern", "/pages/modern", status: 301)
redirect("/pages?type=old", "/pages?type=new", status: 302)
```

The current library won't work on the segments splits. I've created a branch that "works". However this is my first dabble with macros and I'm pretty sure there is a better way to do it. I hope there is.

If you had any pointers or suggestions I'd be more than happy to badger away at it before opening a PR here for your review.  

The draft pr I'm tinkering on is presently here: https://github.com/madebystitched/plug-redirect/pull/1  

I'm pretty sure thee is a better way to do it and I'd love to now have to use a faux option of `query` which is my very blunt lever to query param matching.

Thanks for the library and reading.
C.

**Comment by lpil** [comment]
Hey @colindensem ! Thanks for using this library.

I would recommend publishing a fork as I'm not currently maintaining this library due to focusing on [Gleam](https://github.com/gleam-lang/gleam/) now

Your code looks grand! One thing I will say is that with how it works the ordering of the query string parameters matters, but that may be OK for many uses.

**Comment by colindensem** [comment]
I thought you might be busy with gleam :) When my head has stopped spinning on elixir I'll have to take a peek :) 

> One thing I will say is that with how it works the ordering of the query string parameters matters

I hear that, the fact I kind of made status mandatory is also irking me.  

Thanks for the feedback and quick response.

**Comment by lpil** [comment]
👍  Good luck with your project! If you publish it to GitHub and Hex let me know. We could add a note to the README here recommending your project with its extra features
